version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: dockernhatnguyen/minhnhat.dev.v2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt