version: '3'
services:
  frontend:
    image: dockernhatnguyen/minhnhat.dev
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
