version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./build:/var/www/html
      - ./nginx.conf:/etc/nginx/sites-available/default